# -*- coding: utf-8 -*-
"""pandas profiling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YhuYyyz7wyeG4vslG67_c85oZrC4wIW9
"""

!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
# %matplotlib inline
pd.set_option('display.max_colwidth', None)

df = pd.read_csv('encoded-Football Players Stats (Premier League 2021-2022).csv')
df



# Pandas profiling report
profile = ProfileReport(df, title='Football Players Stats', explorative=True)

# For notebook exploration
profile.to_notebook_iframe()

# export analysis results to an html page, for sharing to a wider audience and non-Jupyter users.
profile.to_file('Football Players Stats.html')